[tool.poetry]
name = "adventofcode2024"
version = "0.1.0"
description = "Advent of Code 2024 Solutions"
authors = ["Evan Allender"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
